name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.PRAVEENTHATI_PRACTICE_SSH_KEY }}" | base64 --decode > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem

      - name: List /tmp directory
        run: ls -l /tmp

      - name: Install Dependencies
        run: |
          cd /home/runner/work/actions_dem0/actions_dem0
          npm install

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ubuntu
          key: /tmp/ec2_key.pem
          port: 22
          script: |
            cd /var/www/html
            sudo rm -rf *
            sudo git clone https://github.com/praveenthati23/actions_dem0.git .
            sudo systemctl restart nginx
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
