name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.PRAVEENTHATI_PRACTICE_SSH_KEY }}" | base64 --decode > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ubuntu
          key: /tmp/ec2_key.pem
          port: 22
          script: |
            cd /var/www/html
            sudo rm -rf *
            sudo git clone https://github.com/praveenthati23/actions_dem0.git .
            # Add any additional deployment commands here
            sudo systemctl restart nginx
